"""Constants for the sinplane game
   Caelan Thomas, 2/09/2016

   This file contains all the constant values for the program -
   so they are all in an easy to access and find place for
   changing later.
"""

CHEAT = False

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 600
WINDOW_TITLE = "Sine Surfer"

CANVAS_BACKGROUND_COLOR = "black"

LOGGING = True

MOVESPEED = 8

PLANE_VELOCITY_MULTIPLIER = 9.65
PLANE_WIDTH = 20
PLANE_HEIGHT = 20
PLANE_STARTING_X = 50
PLANE_COLOR = "red"

SIN_AMPLITUDE = 250
SIN_STARTING_PERIOD = 800
SIN_CHANGE_RATE = 1.05
SIN_PLOT_POINT_DISTANCE = 5
SIN_COLOR = "green"

OBSTACLE_COLOR = "white"

NUMBER_OF_LEVELS = 20

LOGO_Y = 135
LOGO_CLASSIC_Y = 135

# Start menu
START_MENU_BUTTON_WIDTH = 200
START_MENU_BUTTON_HEIGHT = 60
START_MENU_BUTTON_BACKGROUND_COLOR = 'white'
START_MENU_BUTTON_FONT = ("Times", 18)
START_MENU_BUTTON_TEXT_COLOR = 'black'
START_MENU_BUTTON_STARTING_Y_POS = 250
START_MENU_BUTTON_SPACING = 80

# Classic menu
CLASSIC_MENU_BUTTON_X = 67
CLASSIC_MENU_BUTTON_Y = 300
CLASSIC_MENU_BUTTON_WIDTH = 60
CLASSIC_MENU_BUTTON_HEIGHT = 60
CLASSIC_MENU_BUTTON_BG = 'white'
CLASSIC_MENU_BUTTON_FG = 'black'
CLASSIC_MENU_BUTTON_FONT = ("Times", 18)
CLASSIC_MENU_BUTTON_SPACING = 85
CLASSIC_MENU_LOCKED_BG = "gray"
CLASSIC_MENU_LOCKED_FG = "black"
CLASSIC_MENU_FINISHED_BG = "light green"
CLASSIC_MENU_FINISHED_FG = "black"

BACK_X = 450
BACK_Y = 530
BACK_WIDTH = 300
BACK_HEIGHT = 60

# Help menu
HELP_LABEL_Y = 350
HELP_LABEL_FONT = ("Times", 18)
HELP_LABEL_FG = "white"
HELP_LABEL_BG = "black"

# In game
TITLE_FONT = ("Times", 60, "bold")
TITLE_BG = "black"
TITLE_FG = "white"
TITLE_HEIGHT=200